
!###################################################
! WARNING:This is a test auto-generated by KROME, in order to
! show a bare-minimal code to call the KROME's subroutine.
! Most of the values could not be appropriate for your
! problem, since this test is only intended as a general
! purpose example.

program test
  use krome_main !use krome (mandatory)
  use krome_user !use utility (for krome_idx_* constants and others)
  implicit none
  integer,parameter::nsp=krome_nmols !number of species (common)
  real*8::Tgas,dt,x(nsp),spy

  spy = 3.65d2 * 2.4d1 * 3.6d3 !seconds per year

  call krome_init() !init krome (mandatory)
 
  call krome_set_user_crate(0.d0)

  x = (/1.11423458e-01, 6.84091058e-09, 7.51995181e+02, 6.18616142e+01, &
 3.14704239e-04, 1.11419885e-01, 7.62252008e-25, 3.54094921e-11, &
 8.88111752e-51/)

  Tgas = 1d2 !gas temperature (K)
  dt = 1d6 * spy !time-step (s)

  print*, '------- INIT'
  call krome_get_info(x(:),Tgas)

  !call the solver
  call krome(x(:), Tgas, dt) !call KROME

  print*, '-------- FINAL'
  call krome_get_info(x(:),Tgas)

  print *,"Test OK!"

end program test

